<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default30.aspx.cs" Inherits="Default30" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <h1>1. GridView Example with AutoGenerated Column</h1>
<asp:GridView ID ="GridView1" runat="server">

</asp:GridView>
    </form>
</body>
</html>
